### ISSUE TITLE
FE  Actualizar Roomcard (precio y features)

### ISSUE THREAD

**Issue by facundoh86** [maildedani99/nfs_badi#59]

**Comment by MarcosIraola** [comment]
https://www.figma.com/file/NNAgQ5FAKW4pmldVausm5X/Roomi?node-id=1%3A2

![Captura de pantalla de 2020-09-07 20-40-50](https://user-images.githubusercontent.com/32886418/92412113-ef20ce80-f14a-11ea-8a18-0382920805c4.png)
